#############################################################################
# Makefile for building: ShowDemo
# Generated by qmake (2.01a) (Qt 4.8.3) on: ?? ??? 15 20:51:28 2012
# Project:  ShowDemo.pro
# Template: subdirs
# Command: c:\Qt\vs4.8.3\bin\qmake.exe -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o Makefile ShowDemo.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\vs4.8.3\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-ShowDemo \
		sub-DrawWindow \
		sub-MDecoder

ShowDemo\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ShowDemo\ $(MKDIR) ShowDemo\ 
	cd ShowDemo\ && $(QMAKE) g:\ShowDemo\ShowDemo\ShowDemo.pro -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-ShowDemo-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ShowDemo\ $(MKDIR) ShowDemo\ 
	cd ShowDemo\ && $(QMAKE) g:\ShowDemo\ShowDemo\ShowDemo.pro -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-ShowDemo: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE)
sub-ShowDemo-make_default: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) 
sub-ShowDemo-make_first: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) first
sub-ShowDemo-all: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) all
sub-ShowDemo-clean: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) clean
sub-ShowDemo-distclean: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ShowDemo-install_subtargets: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) install
sub-ShowDemo-uninstall_subtargets: ShowDemo\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) uninstall
DrawWindow\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) DrawWindow\ $(MKDIR) DrawWindow\ 
	cd DrawWindow\ && $(QMAKE) g:\ShowDemo\DrawWindow\DrawWindow.pro -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-DrawWindow-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) DrawWindow\ $(MKDIR) DrawWindow\ 
	cd DrawWindow\ && $(QMAKE) g:\ShowDemo\DrawWindow\DrawWindow.pro -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-DrawWindow: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE)
sub-DrawWindow-make_default: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) 
sub-DrawWindow-make_first: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) first
sub-DrawWindow-all: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) all
sub-DrawWindow-clean: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) clean
sub-DrawWindow-distclean: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) distclean
sub-DrawWindow-install_subtargets: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) install
sub-DrawWindow-uninstall_subtargets: DrawWindow\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) uninstall
MDecoder\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MDecoder\ $(MKDIR) MDecoder\ 
	cd MDecoder\ && $(QMAKE) g:\ShowDemo\MDecoder\MDecoder.pro -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-MDecoder-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MDecoder\ $(MKDIR) MDecoder\ 
	cd MDecoder\ && $(QMAKE) g:\ShowDemo\MDecoder\MDecoder.pro -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-MDecoder: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE)
sub-MDecoder-make_default: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) 
sub-MDecoder-make_first: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) first
sub-MDecoder-all: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) all
sub-MDecoder-clean: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) clean
sub-MDecoder-distclean: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) distclean
sub-MDecoder-install_subtargets: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) install
sub-MDecoder-uninstall_subtargets: MDecoder\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: ShowDemo.pro  c:\Qt\vs4.8.3\mkspecs\win32-msvc2008\qmake.conf c:\Qt\vs4.8.3\mkspecs\qconfig.pri \
		c:\Qt\vs4.8.3\mkspecs\modules\qt_webkit_version.pri \
		c:\Qt\vs4.8.3\mkspecs\features\qt_functions.prf \
		c:\Qt\vs4.8.3\mkspecs\features\qt_config.prf \
		c:\Qt\vs4.8.3\mkspecs\features\exclusive_builds.prf \
		c:\Qt\vs4.8.3\mkspecs\features\default_pre.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\default_pre.prf \
		c:\Qt\vs4.8.3\mkspecs\features\debug.prf \
		c:\Qt\vs4.8.3\mkspecs\features\debug_and_release.prf \
		c:\Qt\vs4.8.3\mkspecs\features\default_post.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\default_post.prf \
		c:\Qt\vs4.8.3\mkspecs\features\declarative_debug.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\rtti.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\exceptions.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\stl.prf \
		c:\Qt\vs4.8.3\mkspecs\features\shared.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\embed_manifest_exe.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\embed_manifest_dll.prf \
		c:\Qt\vs4.8.3\mkspecs\features\warn_on.prf \
		c:\Qt\vs4.8.3\mkspecs\features\qt.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\thread.prf \
		c:\Qt\vs4.8.3\mkspecs\features\moc.prf \
		c:\Qt\vs4.8.3\mkspecs\features\win32\windows.prf \
		c:\Qt\vs4.8.3\mkspecs\features\resources.prf \
		c:\Qt\vs4.8.3\mkspecs\features\uic.prf \
		c:\Qt\vs4.8.3\mkspecs\features\yacc.prf \
		c:\Qt\vs4.8.3\mkspecs\features\lex.prf \
		c:\Qt\vs4.8.3\mkspecs\features\include_source_dir.prf
	$(QMAKE) -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o Makefile ShowDemo.pro
c:\Qt\vs4.8.3\mkspecs\qconfig.pri:
c:\Qt\vs4.8.3\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\vs4.8.3\mkspecs\features\qt_functions.prf:
c:\Qt\vs4.8.3\mkspecs\features\qt_config.prf:
c:\Qt\vs4.8.3\mkspecs\features\exclusive_builds.prf:
c:\Qt\vs4.8.3\mkspecs\features\default_pre.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\default_pre.prf:
c:\Qt\vs4.8.3\mkspecs\features\debug.prf:
c:\Qt\vs4.8.3\mkspecs\features\debug_and_release.prf:
c:\Qt\vs4.8.3\mkspecs\features\default_post.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\default_post.prf:
c:\Qt\vs4.8.3\mkspecs\features\declarative_debug.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\rtti.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\exceptions.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\stl.prf:
c:\Qt\vs4.8.3\mkspecs\features\shared.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\embed_manifest_exe.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\embed_manifest_dll.prf:
c:\Qt\vs4.8.3\mkspecs\features\warn_on.prf:
c:\Qt\vs4.8.3\mkspecs\features\qt.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\thread.prf:
c:\Qt\vs4.8.3\mkspecs\features\moc.prf:
c:\Qt\vs4.8.3\mkspecs\features\win32\windows.prf:
c:\Qt\vs4.8.3\mkspecs\features\resources.prf:
c:\Qt\vs4.8.3\mkspecs\features\uic.prf:
c:\Qt\vs4.8.3\mkspecs\features\yacc.prf:
c:\Qt\vs4.8.3\mkspecs\features\lex.prf:
c:\Qt\vs4.8.3\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\vs4.8.3\mkspecs\win32-msvc2008 CONFIG+=declarative_debug -o Makefile ShowDemo.pro

qmake_all: sub-ShowDemo-qmake_all sub-DrawWindow-qmake_all sub-MDecoder-qmake_all FORCE

make_default: sub-ShowDemo-make_default sub-DrawWindow-make_default sub-MDecoder-make_default FORCE
make_first: sub-ShowDemo-make_first sub-DrawWindow-make_first sub-MDecoder-make_first FORCE
all: sub-ShowDemo-all sub-DrawWindow-all sub-MDecoder-all FORCE
clean: sub-ShowDemo-clean sub-DrawWindow-clean sub-MDecoder-clean FORCE
distclean: sub-ShowDemo-distclean sub-DrawWindow-distclean sub-MDecoder-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-ShowDemo-install_subtargets sub-DrawWindow-install_subtargets sub-MDecoder-install_subtargets FORCE
uninstall_subtargets: sub-ShowDemo-uninstall_subtargets sub-DrawWindow-uninstall_subtargets sub-MDecoder-uninstall_subtargets FORCE

sub-ShowDemo-sub_Debug: ShowDemo\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) debug
sub-DrawWindow-sub_Debug: DrawWindow\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) debug
sub-MDecoder-sub_Debug: MDecoder\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-ShowDemo-sub_Debug sub-DrawWindow-sub_Debug sub-MDecoder-sub_Debug

sub-ShowDemo-sub_Release: ShowDemo\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) release
sub-DrawWindow-sub_Release: DrawWindow\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) release
sub-MDecoder-sub_Release: MDecoder\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) release
release: sub-ShowDemo-sub_Release sub-DrawWindow-sub_Release sub-MDecoder-sub_Release

sub-ShowDemo-check: ShowDemo\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ShowDemo\ && $(MAKE) -f $(MAKEFILE) check
sub-DrawWindow-check: DrawWindow\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DrawWindow\ && $(MAKE) -f $(MAKEFILE) check
sub-MDecoder-check: MDecoder\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MDecoder\ && $(MAKE) -f $(MAKEFILE) check
check: sub-ShowDemo-check sub-DrawWindow-check sub-MDecoder-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

